"""
Emits the Godot project files that are pure configuration.

The split is deliberate: the AI writes scenes and scripts (where creativity
belongs), and this module writes project.godot, export_presets.cfg and icon.svg
(where a single wrong key means the project will not open or will not export,
and where an AI adds no value at all).

Verified against Godot 4.7.2.
"""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

GODOT_FEATURES = "4.7"


@dataclass
class GodotPlan:
    """The contract between the AI stage and everything downstream."""
    title: str = "Untitled Game"
    description: str = ""
    main_scene: str = "scenes/Main.tscn"
    window_width: int = 1152
    window_height: int = 648
    autoloads: Dict[str, str] = field(default_factory=dict)
    # path -> declared node paths, used by the manifest assert
    scenes: Dict[str, List[str]] = field(default_factory=dict)
    scripts: List[str] = field(default_factory=list)
    input_actions: Dict[str, List[str]] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Dict) -> "GodotPlan":
        scenes: Dict[str, List[str]] = {}
        for scene in data.get("scenes", []) or []:
            if isinstance(scene, dict) and scene.get("path"):
                scenes[scene["path"]] = [str(n) for n in (scene.get("nodes") or [])]

        scripts: List[str] = []
        for script in data.get("scripts", []) or []:
            if isinstance(script, dict) and script.get("path"):
                scripts.append(script["path"])
            elif isinstance(script, str):
                scripts.append(script)

        autoloads = {
            str(k): str(v) for k, v in (data.get("autoloads") or {}).items()
        }

        window = data.get("window") or {}
        main_scene = data.get("main_scene") or "scenes/Main.tscn"

        return cls(
            title=str(data.get("title") or "Untitled Game"),
            description=str(data.get("description") or ""),
            main_scene=main_scene.replace("res://", ""),
            window_width=int(window.get("width") or 1152),
            window_height=int(window.get("height") or 648),
            autoloads=autoloads,
            scenes=scenes,
            scripts=scripts,
            input_actions=data.get("input_actions") or {},
        )


def _escape(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def write_project_godot(project: Path, plan: GodotPlan) -> None:
    """
    project.godot is INI. Godot omits defaults, so this stays small.
    The leading '*' on an autoload path is what makes it a singleton.
    """
    lines = [
        "; Generated by Mamba. Godot 4.x project manifest.",
        "",
        "config_version=5",
        "",
        "[application]",
        "",
        f'config/name="{_escape(plan.title)}"',
        f'run/main_scene="res://{plan.main_scene}"',
        f'config/features=PackedStringArray("{GODOT_FEATURES}", "GL Compatibility")',
        'config/icon="res://icon.svg"',
    ]

    if plan.autoloads:
        lines += ["", "[autoload]", ""]
        for name, path in plan.autoloads.items():
            target = path if path.startswith("res://") else f"res://{path}"
            lines.append(f'{name}="*{target}"')

    lines += [
        "",
        "[display]",
        "",
        f"window/size/viewport_width={plan.window_width}",
        f"window/size/viewport_height={plan.window_height}",
        'window/stretch/mode="canvas_items"',
        'window/stretch/aspect="expand"',
    ]

    if plan.input_actions:
        lines += ["", "[input]", ""]
        for action, keys in plan.input_actions.items():
            events = ",".join(
                f'Object(InputEventKey,"resource_local_to_scene":false,'
                f'"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,'
                f'"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,'
                f'"pressed":false,"keycode":0,"physical_keycode":{_keycode(k)},'
                f'"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)'
                for k in keys
            )
            lines.append(f'{action}={{')
            lines.append(f'"deadzone": 0.2,')
            lines.append(f'"events": [{events}]')
            lines.append('}')

    lines += [
        "",
        "[rendering]",
        "",
        # gl_compatibility is the safe renderer for web export.
        'renderer/rendering_method="gl_compatibility"',
        'renderer/rendering_method.mobile="gl_compatibility"',
        "",
    ]

    (project / "project.godot").write_text("\n".join(lines), encoding="utf-8")
    logger.debug("Wrote project.godot")


_KEYCODES = {
    "left": 4194319, "right": 4194321, "up": 4194320, "down": 4194322,
    "space": 32, "escape": 4194305, "enter": 4194309, "shift": 4194325,
    "a": 65, "d": 68, "s": 83, "w": 87, "e": 69, "q": 81, "r": 82, "f": 70,
}


def _keycode(key: str) -> int:
    return _KEYCODES.get(str(key).strip().lower(), 0)


def write_export_presets(project: Path, output: str = "dist/index.html") -> None:
    """
    Without this file --export-release fails outright, and the preset name must
    match the command argument exactly.

    thread_support=false matters: single-threaded is the Godot 4 default and
    needs no Cross-Origin-Opener/Embedder-Policy headers, so the preview can be
    served from any static path.
    """
    content = f'''[preset.0]

name="Web"
platform="Web"
runnable=true
advanced_options=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="{output}"
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

custom_template/debug=""
custom_template/release=""
variant/extensions_support=false
variant/thread_support=false
vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=false
html/export_icon=true
html/custom_html_shell=""
html/head_include=""
html/canvas_resize_policy=2
html/focus_canvas_on_start=true
html/experimental_virtual_keyboard=false
progressive_web_app/enabled=false
'''
    (project / "export_presets.cfg").write_text(content, encoding="utf-8")
    logger.debug("Wrote export_presets.cfg")


def write_icon(project: Path, color: str = "#25D366") -> None:
    """project.godot references res://icon.svg; Godot warns loudly without it."""
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" '
        'viewBox="0 0 128 128">'
        f'<rect width="128" height="128" rx="24" fill="{color}"/>'
        '<circle cx="64" cy="64" r="28" fill="#0d0d0d"/>'
        "</svg>"
    )
    (project / "icon.svg").write_text(svg, encoding="utf-8")


def write_ai_files(project: Path, files: Dict[str, str]) -> List[str]:
    """
    Write the AI-authored scenes and scripts. Returns the paths written.
    Paths are confined to the project directory.
    """
    written: List[str] = []
    root = project.resolve()

    for rel_path, content in files.items():
        rel = rel_path.replace("res://", "").lstrip("/")
        target = (project / rel).resolve()
        if root not in target.parents:
            logger.error(f"Refusing to write outside project: {rel_path}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        # GDScript is indentation-sensitive and rejects mixed tabs/spaces.
        if rel.endswith(".gd"):
            content = _normalise_indentation(content)
        target.write_text(content, encoding="utf-8")
        written.append(rel)

    return written


def _normalise_indentation(source: str) -> str:
    """
    Convert leading 4-space groups to tabs. Godot errors on mixed indentation
    within a file, and an AI mixes them regularly.
    """
    out = []
    for line in source.split("\n"):
        stripped = line.lstrip(" \t")
        if not stripped:
            out.append("")
            continue
        indent = line[: len(line) - len(stripped)]
        if "\t" in indent and " " in indent:
            # Mixed: rebuild purely from the visual width.
            width = indent.replace("\t", "    ").count(" ")
            indent = "\t" * (width // 4)
        elif " " in indent:
            indent = "\t" * (len(indent) // 4)
        out.append(indent + stripped)
    return "\n".join(out)


def scaffold(project: Path, plan: GodotPlan, ai_files: Dict[str, str]) -> List[str]:
    """Write a complete project: config from templates, content from the AI."""
    project.mkdir(parents=True, exist_ok=True)
    write_project_godot(project, plan)
    write_export_presets(project)
    write_icon(project)
    written = write_ai_files(project, ai_files)
    logger.info(f"📁 Scaffolded Godot project: {len(written) + 3} files at {project}")
    return written
