extends Node
# Generated by godot_runtime.py — do not edit by hand.
# Runs as an autoload inside the REAL game, so singletons, _ready() and physics
# all behave exactly as they do for a player. A --script SceneTree run does not
# register autoloads and reports false compile failures instead.

const FRAMES := 200
const EXPECT := {"enemy": 8}
const ROLE_WORDS := {"enemy": ["enemy", "enemies", "ghost", "drone", "alien", "monster", "obstacle"], "collectible": ["coin", "collectible", "pellet", "orb", "gem", "star", "cell", "pickup"], "platform": ["platform", "ground", "floor", "wall", "tile", "brick"]}

var _frames := 0
var _player: Node2D = null
var _start := Vector2.ZERO
var _moved := false
var _done := false


func _ready() -> void:
	process_priority = 1000


func _process(_delta: float) -> void:
	if _done:
		return
	_frames += 1

	if _player == null or not is_instance_valid(_player):
		_player = _find_player(get_tree().root)
		if _player != null:
			_start = _player.global_position

	if _player != null:
		var p := _player.global_position
		if not _moved and p.distance_to(_start) > 1.0:
			_moved = true
		if absf(p.x) > 100000.0 or absf(p.y) > 100000.0:
			print("RUNTIME_FAIL PLAYER_LOST player left the world at ", p,
				" - it is falling forever. Check collision shapes and gravity.")
			_finish()
			return

	if _frames >= FRAMES:
		_finish()


func _finish() -> void:
	_done = true
	_check_content()
	if _player == null:
		print("RUNTIME_FAIL NO_PLAYER no node named like a player exists in the scene.")
	elif not _moved:
		print("RUNTIME_FAIL PLAYER_INERT the player never moved in ", FRAMES,
			" frames. It is not affected by gravity and does not respond to input, ",
			"so the game has no working controls.")
	print("RUNTIME_OK frames=", _frames, " player_moved=", _moved)


func _check_content() -> void:
	# The level must contain what the plan promised. An empty container with no
	# spawner passes every structural gate while being an empty game.
	for role in EXPECT.keys():
		var want: int = int(EXPECT[role])
		var found := _count_role(get_tree().root, ROLE_WORDS[role])
		if found == 0:
			print("RUNTIME_FAIL NO_", String(role).to_upper(),
				" the level declares ", want, " ", role,
				" but the running game contains NONE.")
		elif found * 2 < want:
			print("RUNTIME_FAIL TOO_FEW_", String(role).to_upper(),
				" the level declares ", want, " ", role, " but only ", found,
				" exist at runtime.")


func _count_role(n: Node, words: Array) -> int:
	var total := 0
	var lower := String(n.name).to_lower()
	for w in words:
		if lower.contains(String(w)):
			total += 1
			break
	for c in n.get_children():
		total += _count_role(c, words)
	return total


func _find_player(n: Node) -> Node2D:
	if n is Node2D and String(n.name).to_lower().contains("player"):
		return n as Node2D
	for c in n.get_children():
		var found := _find_player(c)
		if found != null:
			return found
	return null
